name: Build and Package
on:
  workflow_call:
    inputs:
      modules:
        description: 'Stringified JSON object listing modules to build'
        required: true
        type: string

      zip_command:
        description: 'A shell command for creating a release zip'
        required: true
        type: string

      config:
        description: 'A CMake build config'
        required: true
        type: string
        default: Release

jobs:
  build-project:
    name: Build ${{ matrix.module }} for ${{ matrix.arch }}-bit architecture
    runs-on: windows-2022
    strategy:
      matrix:
        module: ${{ fromJson(inputs.modules) }}
        arch: [ 32, 64 ]
        include:
          - arch: 32
            platform: Win32
            term: amd64_x86

          - arch: 64
            platform: x64
            term: amd64

    env:
      BUILD_DIR: ${{ github.workspace }}\build\${{ matrix.arch }}\${{ matrix.module }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install and cache the latest CMake
        uses: lukka/get-cmake@latest

      - name: Setup Developer Command Prompt for Microsoft Visual C++.
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.term }}

      - name: Restore build files
        uses: actions/cache@v3
        with:
          path: ${{ env.BUILD_DIR }}
          key: ${{ matrix.module }}-${{ matrix.arch }}-${{ hashFiles( 'CMakeLists.txt' ) }}

      - name: Print build directory tree
        run: tree /f ${{ env.BUILD_DIR }}

      - name: Generate build files
        run: cmake -G "Visual Studio 17 2022" -A "${{ matrix.platform }}" -B "${{ env.BUILD_DIR }}" -DMODULE=${{ matrix.module }}

      - name: Build the project
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ inputs.config }}

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.module }}-${{ matrix.arch }}
          path: ${{ env.BUILD_DIR }}\${{ inputs.config }}\*.dll

  package-project:
    name: Package the artifacts into a release zip
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build-project
    permissions:
      contents: write
    steps:
      - name: Setup version tag
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Setup zip name
        env:
          PROJECT_NAME: ${{ github.event.repository.name }}
        run: echo "ZIP_NAME=$PROJECT_NAME-$VERSION_TAG.zip" >> $GITHUB_ENV

      - name: Install required tools
        run: |
          sudo apt update
          sudo apt install zip tree

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Print artifact tree
        run: tree artifacts

      - name: Make release zip
        run: ${{ inputs.zip_command }}

      - name: Create a release draft
        uses: softprops/action-gh-release@v1
        with:
          body: '# 📑 Changelog'
          draft: true
          prerelease: false
          files: ${{ env.ZIP_NAME }}
          name: Release ${{ env.VERSION_TAG }}
          tag_name: ${{ env.VERSION_TAG }}
          fail_on_unmatched_files: true
